name = "hugo-theme-academic-terminal"
license = "MIT"
licenselink = "https://github.com/GeoffreyChen777/hugo-theme-academic-terminal/blob/master/LICENSE"
description = "A minimal, responsive and light theme for Hugo inspired by Linux console."
homepage = "https://github.com/GeoffreyChen777/hugo-theme-academic-terminal"
tags = ["blog", "academic", "portfolio", "console", "terminal", "clean", "personal", "minimal", "monotone", "simple", "technical", "responsive", "mobile", "minimalist"]
features = ["responsive", "google analytics"]
min_version = "0.81.0"

[author]
    name = "Geoffrey Chen"
    homepage = "https://geoch.top"
    github = "https://github.com/GeoffreyChen777"